import { Inter } from 'next/font/google'
import './globals.css'

import Footer from './Components/footer'
import Header from './Components/header'
import Auth from './Components/Auth'
import Providers from './provider/provider'


const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	weight: ['400', '700'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} antialiased`}>
				<Providers>
				<Header />
				<Auth/>
				{children}
				<Footer />
				</Providers>
			</body>
		</html>
	)
}